# Generated by Django 5.2.8 on 2025-11-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(max_length=50)),
                ('stock_quantity', models.CharField(max_length=10)),
            ],
        ),
    ]
